# Site settings
title: ctrue.name
description: >
  Personal website of Curtis Rueden.
twitter_username: ctrueden
github_username:  ctrueden

# Build settings
markdown: kramdown
theme: minima
sass:
  sass_dir: _sass
kramdown:
  syntax_highlighter: rogue
collections:
  pages:
    output: true
    permalink: /:path
defaults:
  - scope:
      path: "_pages" # NB: all files in the project
      type: pages
    values:
      layout: page
